// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhiucfxvstejtqquywpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoaXVjZnh2c3RlanRxcXV5d3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjg5MjUsImV4cCI6MjA2NjYwNDkyNX0.fHoQqGnUl1aqJ-1F2Nw_P3vUsErnxzF0pluoJ69HoqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);