// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tevycfasojspvsnxvnme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRldnljZmFzb2pzcHZzbnh2bm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzY1NDEsImV4cCI6MjA2NjM1MjU0MX0.EnqwQa_nl6Al-j9UMiSyfQQwFQFeYAryhr0V47vsZ7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);